export enum Tech {
  Javascript = 'Javascript',
  NodeJs = 'NodeJs',
  React = 'React',
  Python = 'Python',
  Angular = 'Angular',
  C = 'C',
  Java = 'Java',
  MongoDB = 'MongoDB',
  SQL = 'SQL',
  Docker = 'Docker',
  Flutter = 'Flutter',
  CSharp = 'C#',
  Typescript = 'Typescript',
  NestJs = 'NestJs',
  PHP = 'PHP',
  HTML = 'HTML',
  CSS = 'CSS',
  MediaPipe = 'MediaPipe',
  MariaDB = 'MariaDB'
}